-- ============================================================
-- NUCLEAR FIX: COALESCE 42804 on map_suggestions INSERT
-- ============================================================
-- The error "COALESCE types uuid and integer cannot be matched"
-- is generated by PostgreSQL internally when combining RLS policies
-- or when a trigger queries the table with type-mismatched columns.
--
-- Root cause possibilities:
--   A) map_suggestions was created via Supabase UI with integer id
--      before the UUID migration ran (CREATE TABLE IF NOT EXISTS skipped it)
--   B) A hidden trigger on the table uses COALESCE with wrong types
--   C) The check_suggestion_rate_limit trigger is evaluated in a context
--      where the map_suggestions.id or another column is integer
--
-- Fix: Drop and recreate everything cleanly.
-- ============================================================


-- STEP 1: Drop ALL triggers on map_suggestions to eliminate hidden COALESCE sources
DROP TRIGGER IF EXISTS suggestion_rate_limit ON public.map_suggestions;
DROP FUNCTION IF EXISTS public.check_suggestion_rate_limit();

-- Also drop any Supabase auto-generated triggers (moddatetime, etc.)
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT trigger_name
        FROM information_schema.triggers
        WHERE event_object_schema = 'public'
          AND event_object_table = 'map_suggestions'
    LOOP
        EXECUTE 'DROP TRIGGER IF EXISTS ' || quote_ident(r.trigger_name) || ' ON public.map_suggestions';
    END LOOP;
END;
$$;


-- STEP 2: Drop ALL RLS policies on map_suggestions
DROP POLICY IF EXISTS "suggestions_insert" ON public.map_suggestions;
DROP POLICY IF EXISTS "suggestions_read" ON public.map_suggestions;
DROP POLICY IF EXISTS "suggestions_delete" ON public.map_suggestions;
DROP POLICY IF EXISTS "suggestions_owner_read" ON public.map_suggestions;
DROP POLICY IF EXISTS "suggestions_contributor_read" ON public.map_suggestions;

-- Disable RLS temporarily
ALTER TABLE public.map_suggestions DISABLE ROW LEVEL SECURITY;


-- STEP 3: Check if id column is integer and fix it
-- We do this safely: rename old table, create new one, copy data, rename back
DO $$
DECLARE
    id_type TEXT;
BEGIN
    SELECT data_type INTO id_type
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'map_suggestions'
      AND column_name = 'id';

    IF id_type IS NULL THEN
        RAISE NOTICE 'Table map_suggestions does not exist, will be created fresh.';
    ELSIF id_type != 'uuid' THEN
        RAISE NOTICE 'map_suggestions.id is %, not uuid. Recreating table.', id_type;

        -- Save existing data to temp table
        CREATE TEMP TABLE _ms_backup AS SELECT * FROM public.map_suggestions;

        -- Drop constraints and the table
        DROP TABLE public.map_suggestions CASCADE;

        -- Recreate with correct UUID schema
        CREATE TABLE public.map_suggestions (
            id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            map_id          UUID NOT NULL REFERENCES public.maps(id) ON DELETE CASCADE,
            contributor_id  UUID NOT NULL,
            contributor_name TEXT NOT NULL DEFAULT 'Anonymous',
            map_data        JSONB NOT NULL,
            created_at      TIMESTAMPTZ DEFAULT now()
        );

        RAISE NOTICE 'Table recreated with UUID id. Old data lost (type incompatible).';
    ELSE
        RAISE NOTICE 'map_suggestions.id is already uuid. Schema is correct.';

        -- Just ensure contributor_id is UUID too
        -- (Can't easily ALTER UUID columns if data exists, but can check)
    END IF;
END;
$$;


-- STEP 4: Ensure table exists with correct schema (idempotent)
CREATE TABLE IF NOT EXISTS public.map_suggestions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    map_id          UUID NOT NULL REFERENCES public.maps(id) ON DELETE CASCADE,
    contributor_id  UUID NOT NULL,
    contributor_name TEXT NOT NULL DEFAULT 'Anonymous',
    map_data        JSONB NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT now()
);

-- Remove the note column if it exists (was causing type issues before)
ALTER TABLE public.map_suggestions DROP COLUMN IF EXISTS note;

-- Ensure indexes
CREATE INDEX IF NOT EXISTS idx_suggestions_map ON public.map_suggestions(map_id);
CREATE INDEX IF NOT EXISTS idx_suggestions_contributor ON public.map_suggestions(contributor_id);


-- STEP 5: Re-enable RLS with clean, simple policies (NO COALESCE-inducing subqueries)
ALTER TABLE public.map_suggestions ENABLE ROW LEVEL SECURITY;

-- Owner reads all suggestions for their maps
-- IMPORTANT: use a simple EXISTS, not a correlated subquery that might trigger COALESCE
CREATE POLICY "suggestions_owner_read" ON public.map_suggestions
    FOR SELECT USING (
        auth.uid() IS NOT NULL AND (
            auth.uid() = contributor_id
            OR auth.uid() = (SELECT user_id FROM public.maps WHERE id = map_suggestions.map_id LIMIT 1)
        )
    );

-- Only map owner can delete suggestions
CREATE POLICY "suggestions_delete" ON public.map_suggestions
    FOR DELETE USING (
        auth.uid() IS NOT NULL AND
        auth.uid() = (SELECT user_id FROM public.maps WHERE id = map_suggestions.map_id LIMIT 1)
    );

-- NOTE: INSERT is intentionally left to the RPC function only (no direct INSERT policy)
-- The submit_map_suggestion RPC (SECURITY DEFINER) handles all inserts.


-- STEP 6: Drop and recreate the safe RPC (now without any triggers to worry about)
DROP FUNCTION IF EXISTS public.submit_map_suggestion(UUID, UUID, TEXT, JSONB);

CREATE OR REPLACE FUNCTION public.submit_map_suggestion(
    p_map_id            UUID,
    p_contributor_id    UUID,
    p_contributor_name  TEXT,
    p_map_data          JSONB
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_caller_uid    UUID;
    v_link_active   BOOLEAN;
    v_rate_count    BIGINT;
    v_new_id        UUID;
BEGIN
    -- 1. Auth check
    v_caller_uid := auth.uid();
    IF v_caller_uid IS NULL THEN
        RETURN json_build_object('ok', false, 'error', 'Not authenticated');
    END IF;

    IF v_caller_uid <> p_contributor_id THEN
        RETURN json_build_object('ok', false, 'error', 'contributor_id mismatch');
    END IF;

    -- 2. Active collab link check (direct query, no RLS since SECURITY DEFINER as postgres)
    SELECT EXISTS (
        SELECT 1 FROM public.map_collab_links
        WHERE map_collab_links.map_id = p_map_id
          AND map_collab_links.is_active = true
    ) INTO v_link_active;

    IF NOT v_link_active THEN
        RETURN json_build_object('ok', false, 'error', 'No active collab link');
    END IF;

    -- 3. Rate limit check
    SELECT COUNT(*)::BIGINT INTO v_rate_count
    FROM public.map_suggestions
    WHERE map_id = p_map_id
      AND contributor_id = p_contributor_id;

    IF v_rate_count >= 20 THEN
        RETURN json_build_object('ok', false, 'error', 'Rate limit: max 20 suggestions per map');
    END IF;

    -- 4. Insert (no RLS, no problematic triggers)
    INSERT INTO public.map_suggestions (map_id, contributor_id, contributor_name, map_data)
    VALUES (p_map_id, p_contributor_id, p_contributor_name, p_map_data)
    RETURNING id INTO v_new_id;

    RETURN json_build_object('ok', true, 'id', v_new_id);
END;
$$;

-- Grant to both roles (auth.uid() check inside blocks unauthenticated access)
GRANT EXECUTE ON FUNCTION public.submit_map_suggestion(UUID, UUID, TEXT, JSONB) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_map_suggestion(UUID, UUID, TEXT, JSONB) TO anon;


-- STEP 7: Same fix for the "archive" insert done by the map owner
-- The map owner also needs to insert into map_suggestions when swapping versions.
-- We handle this with a separate RPC that checks owner instead of collab link.
DROP FUNCTION IF EXISTS public.archive_map_version(UUID, UUID, TEXT, JSONB);

CREATE OR REPLACE FUNCTION public.archive_map_version(
    p_map_id            UUID,
    p_owner_id          UUID,
    p_label             TEXT,
    p_map_data          JSONB
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_caller_uid    UUID;
    v_is_owner      BOOLEAN;
    v_new_id        UUID;
BEGIN
    v_caller_uid := auth.uid();
    IF v_caller_uid IS NULL THEN
        RETURN json_build_object('ok', false, 'error', 'Not authenticated');
    END IF;

    -- Verify the caller is the actual map owner
    SELECT EXISTS (
        SELECT 1 FROM public.maps WHERE id = p_map_id AND user_id = v_caller_uid
    ) INTO v_is_owner;

    IF NOT v_is_owner THEN
        RETURN json_build_object('ok', false, 'error', 'Not the map owner');
    END IF;

    INSERT INTO public.map_suggestions (map_id, contributor_id, contributor_name, map_data)
    VALUES (p_map_id, v_caller_uid, p_label, p_map_data)
    RETURNING id INTO v_new_id;

    RETURN json_build_object('ok', true, 'id', v_new_id);
END;
$$;

GRANT EXECUTE ON FUNCTION public.archive_map_version(UUID, UUID, TEXT, JSONB) TO authenticated;


-- DONE
-- Run the diagnostic below to verify everything is correct:
SELECT column_name, data_type, udt_name
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'map_suggestions'
ORDER BY ordinal_position;
